# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PMD Code Analysis

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '32 14 * * 6'
  workflow_dispatch:  # Permet de lancer manuellement

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run PMD
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false
          version: '7.0.0-rc4'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif